Thomasdezeeuw/heph

examples/1_hello_world.rs, examples/4_sync_actor.rs, examples/6_process_signals.rs, src/actor/mod.rs, src/actor/sync.rs, src/actor/tests.rs, src/actor_ref/mod.rs, src/actor_ref/tests.rs, src/inbox/mod.rs, src/net/tcp/server.rs, src/rt/coordinator.rs, src/rt/mod.rs, src/rt/process/tests.rs, src/rt/worker.rs, tests/functional.rs, tests/functional/actor_ref.rs, tests/functional/from_message.rs, tests/functional/tcp/stream.rs, tests/regression/issue_145.rs, tests/regression/issue_294.rs
Renames `{ActorRef,ActorGroup}::send` to `try_send`.
Fixes #277.
=> Add ActorRef::send

tests/examples.rs, tests/functional/from_message.rs
=> Ignore test_6_process_signals on Linux 

src/actor/mod.rs, src/actor/tests.rs, src/rt/mod.rs, src/rt/process/actor.rs, src/rt/process/mod.rs, src/rt/scheduler/local/inactive.rs, src/rt/scheduler/mod.rs, src/rt/scheduler/shared/inactive.rs, src/rt/scheduler/shared/runqueue.rs, src/rt/scheduler/tests.rs
Help with debugging, the name is read from the type which is done on a
best effort basis.
Changes the (trace) log output from something like:
```log
2020-11-24T16:54:20.682129Z [DEBUG] heph::rt: spawning thread-local actor: pid=140456139703328
2020-11-24T16:54:20.682294Z [TRACE] heph::rt::scheduler: running process: pid=140456139703328
2020-11-24T16:54:20.682336Z [TRACE] heph::rt::scheduler: finished running process: pid=140456139703328, elapsed_time=16.002µs, result=Complete
```
To
```log
2020-11-24T16:54:20.682129Z [DEBUG] heph::rt: spawning thread-local actor: pid=140456139703328, name=greeter_actor
2020-11-24T16:54:20.682294Z [TRACE] heph::rt::scheduler: running process: pid=140456139703328, name=greeter_actor
2020-11-24T16:54:20.682336Z [TRACE] heph::rt::scheduler: finished running …
```
=> Add actor name to logging

README.md, src/lib.rs, src/rt/channel.rs, src/rt/coordinator.rs, src/rt/sync_worker.rs, src/rt/worker.rs, tests/message_loss.rs, tests/regression.rs, tests/regression/issue_323.rs, tests/util/mod.rs
If a sync actor is short running, or the time before calling
Runtime::start takes a while, the thread running the sync actor could be
done before the coordinator had a chance to register it. This causes the
coordinator to never receive an event for it on FreeBSD (it does receive
an event on macOS and Linux) and never remove it from the list of sync
actors, causing the runtime to run for ever.
The fix is fairly simple: after registering check if the sync worker is
still alive by trying to write zero bytes to its pipe.
Fixes #323.
=> Fix missing event from short running sync actors

src/actor_ref/mod.rs, src/rt/coordinator.rs, tests/functional/actor_group.rs
This allows the user to specify how to send the message: send it to all
actors in the group, or to only one.
Fixes #303.
=> Add Delivery kind to ActorGroup::try_send

src/net/tcp/stream.rs, tests/functional/tcp/stream.rs, tests/util/mod.rs
The `send` and `try_recv` tests on Linux were a bit flaky, often making more progress than expected. Adding more stages to the actor as well as more points to return pending fixes this.
This also adds two tests for the connecting of the `TcpStream`.
=> Fix flaky TCP send and try_recv tests on Linux

.gitignore, Makefile, doc/Trace Format.md, examples/8_tracing.rs, examples/README.md, src/rt/coordinator.rs, src/rt/error.rs, src/rt/mod.rs, src/rt/scheduler/mod.rs, src/rt/trace.rs, src/rt/worker.rs, tools/Cargo.toml, tools/src/bin/convert_trace.rs
Alternative to  #330. #330 collects the metrics in memory to expose them (somehow) at some point. This implementation writes events the moment they happen.
It currently writes a JSON (like) trace to a file, but it needs to use a proper (standardised) format. This an example of running the Hello World example:
```log
{"stream_id":0,"description":"Creating worker threads","start":1609960949727107000,"elapsed":"137.218µs","attributes":{"amount":"1"}}
{"stream_id":1,"description":"Initialising the worker thread","start":1609960949727290000,"elapsed":"65.237µs","attributes":{}}
{"stream_id":0,"description":"Initialising the coordinator thread","start":1609960949727345000,"elapsed":"27.821µs","attributes":{}}
{"stream_id":0,"description":"Polling for OS …
```
=> Add basic trace infrastructure

tests/examples.rs
It appears that Cargo already does this for us, so we don't have to
any more.
Reduces the runtime of the example tests from 12-16s to 0.5s.
Closes #310.
=> Don't build examples in example tests

src/actor/sync.rs, tests/functional/sync_actor.rs
The thread parking implementation for Linux using futex which could be
considerably faster than our generic locking implementation. By
happenstance the generic implementation looks a lot like the old
implementation, but now we don't have to worry about it functioning
correctly.
=> Change task::Waker impl for sync actor to be based on thread parking

Cargo.toml, Makefile, examples/2_my_ip.rs, examples/7_restart_supervisor.rs, src/actor/mod.rs, src/actor/sync.rs, src/actor_ref/rpc.rs, src/lib.rs, src/net/mod.rs, src/net/tcp/listener.rs, src/net/tcp/server.rs, src/net/tcp/stream.rs, src/net/udp.rs, src/rt/scheduler/tests.rs, src/supervisor.rs, src/test.rs, src/timer.rs, tests/functional.rs, tests/functional/runtime.rs, tests/functional/tcp/stream.rs, tests/functional/udp.rs
This implements vectored I/O for UdpSocket and TcpStream based on the socket2 crate.
Adds the following API:
* `net::MaybeUninitSlice` structure.
* `net::BytesVectored` structure.
For `TcpStream`:
* `TcpStream::try_send_vectored`
* `TcpStream::send_vectored`
* `TcpStream::send_vectored_all`
*  `TcpStream::try_recv_vectored`
* `TcpStream::recv_vectored`
* `TcpStream::recv_n_vectored`
For `UdpSocket`:
* `UdpSocket::try_send_to_vectored`
* `UdpSocket::send_to_vectored`
* `UdpSocket::try_send_vectored`
* `UdpSocket::send_vectored`
* `UdpSocket::try_recv_from_vectored`
* `UdpSocket::recv_from_vectored`
* `UdpSocket::try_peek_from_vectored`
* `UdpSocket::peek_from_vectored`
* `UdpSocket::try_recv_vectored`
* `UdpSocket::recv_vectored`
* `UdpSocket::try_peek_vectored`
* …
=> Implement vectored I/O for net types

src/net/tcp/stream.rs, src/test.rs, tests/functional/tcp/stream.rs
Contains the following methods:
* TcpStream::try_peek
* TcpStream::peek
* TcpStream::try_peek_vectored
* TcpStream::peek_vectored
Closes #304.
=> Add peeking to TcpStream

src/rt/coordinator.rs, src/rt/mod.rs, src/rt/trace.rs, src/rt/worker.rs
This reduces the binary size by roughly 30k. This is also a decent step
into an API that can be publicly exposed.
Closes  #346.
TODO:
=> Change tracing events to use trait objects

Cargo.toml, examples/2_my_ip.rs, examples/7_restart_supervisor.rs, examples/99_stress_memory.rs, src/actor/mod.rs, src/log.rs, src/net/tcp/listener.rs, src/net/tcp/server.rs, src/net/udp.rs, src/supervisor.rs
Std-logger isn't really a required feature, if users want to use another
logging implementation this would just include dead code.
Reduces the number of crates from 56 to 37 crates when building without
features.
Removes the following API:
* log::init
* log::try_init
* log::request
* log::REQUEST_TARGET
=> Move std-logger to dev-dependency

examples/7_restart_supervisor.rs, src/supervisor.rs, tests/functional/restart_supervisor.rs
Changes the generated `new` function to accept no arguments when a unit arguments is used as `NewActor::Argument`. Also changes the generated `new` function to accept each part of the tuple as an argument, rather than a single argument with the complete tuple.
This also removes the `default` options as there are too many branches already.
Closes #302.
Closes #314.
=> Improve restart_supervisor! ergonomics

Cargo.toml, src/actor/context.rs, src/lib.rs, src/net/tcp/listener.rs, src/net/udp.rs, src/rt/process/tests.rs, src/rt/scheduler/tests.rs, src/test.rs, src/timer.rs, src/util.rs, tests/functional/actor_ref.rs, tests/functional/tcp/listener.rs, tests/functional/tcp/stream.rs, tests/functional/timer.rs, tests/functional/udp.rs, tests/util/mod.rs
Removes all future-* crates as dependencies.
Reduce the number of crates to build from 86 to 63 (when testing). Also reduces the `cargo check` from 26.58s to 19.19s.
Includes #367.
Includes #368.
=> Remove futures crates as depdencies

src/rt/coordinator.rs, src/rt/mod.rs, src/rt/scheduler/mod.rs, src/rt/scheduler/shared/mod.rs, src/rt/scheduler/tests.rs, src/test.rs
Removes an `Arc` from the shared scheduler and timers.
=> Internal cleanup

examples/1_hello_world.rs, examples/3_rpc.rs, examples/6_process_signals.rs, examples/8_tracing.rs, examples/99_stress_memory.rs, src/actor/context.rs, src/actor/mod.rs, src/actor_ref/mod.rs, src/actor_ref/rpc.rs, src/lib.rs, src/log.rs, src/rt/mod.rs, src/rt/process/tests.rs, src/rt/scheduler/tests.rs, src/rt/shared/scheduler/tests.rs, src/supervisor.rs, src/test.rs, src/timer.rs, tests/functional.rs, tests/functional/actor.rs, tests/functional/actor_context.rs, tests/functional/actor_group.rs, tests/functional/actor_ref.rs, tests/functional/from_message.rs, tests/functional/tcp/listener.rs, tests/functional/tcp/server.rs, tests/functional/tcp/stream.rs, tests/functional/timer.rs, tests/message_loss.rs
This allows us to drop `Result<(), !>` as return type from many simple
actors.
Updates #164 (already closed).
=> Implement Actor for async functions without result

src/rt/mod.rs
The name is optionally provided in `SyncActorOptions`.
=> Add sync actor name to debug logging

examples/README.md, tools/src/bin/convert_trace.rs
If the output argument is not provided it will use the input path with
the extension replaced with ".json".
=> Make the output argument of convert_trace optional

src/rt/coordinator.rs, src/rt/shared/mod.rs, src/rt/shared/waker.rs, src/rt/timers.rs, src/rt/worker.rs, src/test.rs
Instead of letting the coordinator schedule thread-safe actors based on
the shared timers this commit changes the workers to schedule the
thread-safe actors.
This does introduce the "Thundering herd problem" for the shared timers
if multiple worker threads have the same timeout (based on the shared
timers) and all attempt to schedule the same thread-safe actor because
of it.
=> Move scheduling based on shared timers to workers

src/actor/context.rs, src/timer.rs, tests/functional/timer.rs
Renames the following methods:
* `Timer::new` to `Timer::at`.
* `Timer::timeout` to `Timer::after`.
* `Deadline::new` to `Deadline::at`.
* `Deadline::timeout` to `Deadline::after`.
* `Interval::new` to `Interval::every`.
=> Rename timer methods

src/log.rs, src/rt/process/mod.rs, src/supervisor.rs
Now the module only serves as documentation.
This means we'll no longer be tied to a fixed version of the log crate.
Closes  #390.
=> Don't export log macros in log module

examples/2_my_ip.rs, examples/6_process_signals.rs, src/actor/mod.rs, src/actor/tests.rs, src/net/tcp/server.rs, src/rt/local/scheduler/mod.rs, src/rt/local/scheduler/tests.rs, src/rt/mod.rs, src/rt/process/actor.rs, src/rt/process/tests.rs, src/rt/shared/mod.rs, src/rt/shared/scheduler/mod.rs, src/rt/shared/scheduler/tests.rs, src/test.rs, src/timer.rs, tests/functional/actor_context.rs, tests/functional/restart_supervisor.rs, tests/functional/runtime.rs, tests/functional/test.rs, tests/functional/udp.rs
Removes the `actor::context` module.
=> Move ThreadLocal and ThreadSafe into the actor module

src/actor/mod.rs, src/rt/coordinator.rs, src/rt/mod.rs, src/rt/process/actor.rs, src/rt/shared/mod.rs, src/rt/signal.rs, src/rt/waker.rs, src/rt/worker.rs
Returns the name of the actor.
The default implementation creates a name based on the type name,
something that was already used to log messages.
Closes #6 (already closed).
Updates #271.
=> Add NewActor::actor

examples/6_process_signals.rs, src/actor/context.rs, src/actor/mod.rs, src/actor/spawn.rs, src/net/tcp/listener.rs, src/net/tcp/server.rs, src/net/tcp/stream.rs, src/net/udp.rs, src/rt/access.rs, src/rt/local/scheduler/mod.rs, src/rt/local/scheduler/tests.rs, src/rt/mod.rs, src/rt/process/actor.rs, src/rt/process/mod.rs, src/rt/process/tests.rs, src/rt/shared/mod.rs, src/rt/shared/scheduler/mod.rs, src/rt/shared/scheduler/tests.rs, src/rt/sync_worker.rs, src/test.rs, src/timer.rs, tests/functional/actor_context.rs, tests/functional/restart_supervisor.rs, tests/functional/runtime.rs, tests/functional/tcp/server.rs, tests/functional/test.rs, tests/functional/udp.rs
Renames `actor::Context` to `actor::RuntimeAccess`
The original Context name was quite misleading as it was just a part of
the `actor::Context`. The new runtime `RuntimeAccess`, with generic
parameter name RT, is a better fit as it indicates what kind of runtime
access the actor needs.
Renames `rt::process::ContextKind` to `RuntimeSupport`
Moves `actor::ThreadSafe` to `rt::access::ThreadSafe`.
Moves `actor::ThreadLocal` to `rt::access::ThreadLocal`.
Removes `actor::Context::(try_)spawn` for `ThreadSafe`
This is already implemented via the Spawn trait. So all users have to do
is `use heph::actor::Spawn` and they have the same functionality.
Finally it changes `actor::Context::runtime` to return the generic parameter
For `ThreadLocal` this doesn't change must as Deref(Mut)<Target = …
=> Move actor::Thread{Safe,Local} to rt::access::Thread{Safe,Local}

src/actor/context.rs, src/lib.rs, src/rt/access.rs, src/rt/local/mod.rs, src/rt/mod.rs, src/rt/shared/mod.rs, src/rt/timers.rs, src/test.rs, src/timer.rs, tests/functional.rs, tests/functional/tcp/listener.rs, tests/functional/tcp/server.rs, tests/functional/timer.rs, tests/util/mod.rs
TODO:
Changes:
* Implements `Clone` for `ThreadLocal` and `ThreadSafe`.
* Remove timer from `Timer`, `Deadline` and `Interval` on `Drop`.
* Add support for thread-safe actors in `Interval`.
Adds  `rt::PrivateAccess::change_deadline` for changing an existing deadline, as
using by the `actor::Bound` implementations in the `timer` module. The current
implementation is removing and than adding the timer, but in the future this can
be improved.
Closes #315.
Closes #282.
=> Improve timer usability

src/actor/mod.rs, src/net/tcp/listener.rs, src/net/tcp/stream.rs, src/net/udp.rs, src/timer.rs, tests/functional/tcp/listener.rs
This is now moved to the implementation sites.
This is another step in removing references to the rt module from the
actor module.
=> Remove trait requirement from actor::Bound

Cargo.toml, tests/examples.rs
Also disables the timestamp feature as that isn't as useful when testing
locally. And enables to nightly feature, since Heph is nightly only at
the moment anyway.
=> Update to std-logger v0.4.0

src/rt/access.rs, src/rt/local/scheduler/mod.rs, src/rt/local/scheduler/tests.rs, src/rt/mod.rs, src/rt/process/actor.rs, src/rt/process/future.rs, src/rt/process/mod.rs, src/rt/process/tests.rs, src/rt/shared/mod.rs, src/rt/shared/scheduler/mod.rs, src/rt/shared/scheduler/tests.rs, src/rt/shared/waker.rs, src/spawn/mod.rs, src/spawn/options.rs, tests/functional.rs, tests/functional/future.rs, tests/util/mod.rs
Adds the following methods:
* Runtime::spawn_future
* RuntimeRef::spawn_future
* RuntimeRef::spawn_local_future
* ThreadSafe::spawn_future
Adds `FutureOptions`: ptions for spawning a Future.
Adds `FutureProcess`: a `Process` implementation for `Future`s.
Closes #404.
=> Add ability to spawn Futures to the runtime

tools/src/bin/convert_trace.rs
Although Chrome's Trace Event Format uses microsecond granularity is
does support floating point numbers. So with that we can increase the
granularity from microseconds to nanoseconds.
=> Add nanosecond granularity to trace converter

src/net/mod.rs, src/net/tcp/stream.rs, tests/functional/bytes.rs
Removes the `Bytes` impl for arrays and slices
The `update_length` function was never correctly implemented for them
which causes issues with methods such as `TcpStream::recv_n`.
Closes #308 as this is no longer desidered.
Closes #408 as this is no longer possible.
Don't remove empty buffers in `TcpStream::try_recv_vectored`.
Closes #407.
=> Remove `Bytes` impl for arrays and slices

src/rt/coordinator.rs, tests/examples.rs
It turns out that on Linux, and possible other Unixes,
pthread_sigmask(3) must be called before spawning the worker threads to
ensure that the worker threads inherit the blocked signals.
On the BSDs, and other Unixes supporting kqueue(2), this isn't a problem
as Mio-signals uses sigaction(2) on those OSs.
=> Fix process signal handling on Linux

Cargo.toml, benches/timers_container/Cargo.toml, benches/timers_container/README.md, benches/timers_container/bench.rs
It focusses on three operations:
* Removing the next timer to expire.
* Adding a new timer, with an expectation that the deadline is after the last
deadline added.
* Removing an arbitrary timer.
=> Add benchmarks container used in timers

src/rt/coordinator.rs, src/rt/local/mod.rs, src/rt/local/timers.rs, src/rt/shared/mod.rs, src/rt/shared/timers.rs, src/rt/shared/waker.rs, src/test.rs, src/timer.rs
This is roughly the same implementation as local::Timers, but uses locks
internally allowing the lock around the entire structure to be removed.
Since the locks, and the critical sections that hold them, are smaller
this should improve the performance.
This fixes the "Thundering herd problem" problem by considering the
shared timers only in a single worker at a time. That worker will than
process the shared timers and wakes other workers if needed.
This will create a wave of activity, multiple workers waking up to
access the shared scheduler, but at least they'll have something to do.
Closes #284, #383.
=> Add shared::Timers

Cargo.toml, doc/Trace Format.md, examples/8_tracing.rs, src/actor/sync.rs, src/rt/access.rs, src/rt/coordinator.rs, src/rt/local/mod.rs, src/rt/mod.rs, src/rt/setup.rs, src/rt/shared/mod.rs, src/rt/shared/waker.rs, src/rt/sync_worker.rs, src/rt/worker.rs, src/spawn/mod.rs, src/test.rs, src/trace.rs, tools/src/bin/convert_trace.rs
This trait allows actors to create their own trace events. It's implemented for
actor::Context and SyncContext. Removes the existing SyncContext::start_trace
and SyncContext::finish_trace methods.
To support trace events from async actors that don't interfere with the events
from the runtime this adds substreams to the trace format.
In the convertion to Chrome's Trace Event Format we'll now start using
pids (process ids) for the threads and tid (thread ids) for the actors.
This way we don't have trace events that block each other, e.g. from two
actors who are multiplexed on the same worker thread.
Also implements trace::AttributeValue for NonZero* integers.
The commits have more details.
Closes #345.
Closes #31.
=> Add Trace trait

src/rt/access.rs, src/rt/mod.rs, src/rt/shared/mod.rs, src/spawn/mod.rs, tests/functional.rs, tests/functional/spawn.rs
This allows thread-local actor to spawn thread-safe actors directly from
their `actor::Context`. Note that this was already possible by first
access the `RuntimeRef`.
Updates #311.
=> Implement Spawn<ThreadSafe> for ThreadLocal

src/actor/mod.rs, src/actor_ref/rpc.rs, src/rt/local/mod.rs, src/rt/thread_waker.rs, tests/regression/issue_145.rs
This problem was highlighted by the example in `src/actor_ref/rpc`, line
86. However it had nothing to do with RPC or `ActorRef`s and everything to
do with a race in the use of `ThreadWaker`.
Before polling we first determine the timeout to use based on local and
shared resources, i.e. the schedulers, timers and wake-up mechanisms.
After we determined the timeout we mark ourselves as polling iff the
timeout is not zero.
However it could be that between those two calls (`determine_timeout`
and `mark_polling`) we received e.g. a wake-up event but didn't consider
it in `determine_timeout`. But because we didn't mark ourselves as
polling yet we also won't be awoken from polling, causing us to poll for
ever, missing the wake-up. That would look something like the following:
```
Thread 0 …
```
=> Fix race between determining timeout and marking as polling

tests/functional/timer.rs
The timeout was too small, which in some runs caused the deadline to
already be passed before it could be send to the second actor.
Also fixes the test name.
=> Deflake timers_dont_trigger_after_actor_bound

Cargo.toml, src/actor/context.rs, src/actor/sync.rs, src/actor_ref/mod.rs, src/actor_ref/rpc.rs, src/rt/local/scheduler/mod.rs, src/rt/mod.rs, src/rt/process/actor.rs, src/rt/shared/mod.rs, src/rt/shared/scheduler/mod.rs, src/rt/sync_worker.rs, src/test.rs
It's now named heph-inbox, because I couldn't think of a better name
(that was not taken).
=> Use release version of the inbox crate

src/rt/shared/scheduler/inactive.rs, tests/functional/actor_context.rs, tests/process_signals.rs
In `Inactive::add_branches` it failed to reuse the branch if the
`compare_exchange` failed (to add the branch to the tree). The caused the
created `Branch` to be leaked.
=> Fix memory leak in shared::Scheduler

Cargo.toml, Makefile, src/rt/local/scheduler/tests.rs, src/rt/shared/scheduler/inactive.rs, src/test.rs, tests/examples.rs, tests/functional/actor_context.rs
Commits:
* Removes the `actor_context::runtime` test. It leak memory and didn't actually test much.
* Removed unneeded `RefCell` from test `Runtime`. We only need an immutable reference to it in runtime.
* Don't leak `actor::Context` in `assert_actor_process_unmoved` test.
* Reduce load strength of atomic store operations in `shared::Inactive`, from `SeqCst` to `AcqRel`.
* Update heph-inbox to v0.1.1.
* Fix `RUSTUP_TARGET` var in Makefile.
Although it's often referred to as a target-"triple", in some case it's
actually four fields. For example for GNU/Linux the value is
"x86_64-unknown-linux-gnu".
This change include the last part (-gnu) in the RUSTUP_TARGET variable,
but keeps working for targets with only three parts, such as
"x86_64-apple-darwin".
* Add `test_sanitiser` Make target. …
=> Various commits

src/rt/channel.rs, src/rt/local/mod.rs, src/rt/worker.rs
Since the worker thread never sends a message to the coordinator there
is no point in it registering the receiving side, the same goes for the
worker with the sending side. This reduces the amount of events
generated.
=> Don't register both sides of the rt::channel

src/rt/coordinator.rs, src/rt/local/mod.rs, src/rt/shared/mod.rs, src/rt/shared/waker.rs, src/test.rs, tests/functional/tcp/listener.rs, tests/regression/issue_294.rs
This shared `Poll` instance allows us to register the shared I/O sources
with a single poll, but allows the worker threads to handle the events.
This means that coordinator no longer has to process any events for the
shared processes. This leaves the coordinator to watch over the worker
and sync worker threads.
=> Add shared Poll instance to shared::RuntimeInternals

src/rt/channel.rs, src/rt/coordinator.rs, src/rt/local/mod.rs, src/rt/shared/mod.rs, src/rt/shared/waker.rs, src/rt/worker.rs, src/test.rs
Has the following commits.
Change rt::channel to be a single direction channel
The previous implementation used two pipes and two in-memory channel to
be able to send messages between the coordinator and worker threads.
However so far it's not been needed to send a message from the worker to
the coordinator.
Since it's not needed simple remove on of the pipes and channels,
turning rt::channel into a single direction channel.
Implement fmt::Debug for local::Control message
Various small doc improvements to rt::coordinator
Move creation of Timers and Scheduler to shared::RuntimeInternals::new
Neither are used outside of the function, so might as well create them
in shared::RuntimeInternals::new
Remove Worker::handle_messages
Even though it was technically possible to call it served no …
=> Cleanup work in runtime

src/actor/sync.rs, src/rt/local/timers.rs, src/rt/shared/mod.rs, src/rt/shared/timers.rs, src/rt/signal.rs, src/spawn/mod.rs
This still documented when sync actors received process signals
automatically, but this is no longer the case.
=> Update process signals docs

src/actor_ref/mod.rs, src/lib.rs, src/rt/shared/mod.rs, src/rt/shared/scheduler/inactive.rs, src/rt/thread_waker.rs, src/rt/waker.rs, src/test.rs, src/trace.rs
In the past the *correct* use of atomics is trickier than it first
seems. It often requires checking the assembly for correctness and it
requires knowing what other locations access the same memory.
This commit documents all atomic operations that don't use `SeqCst` why
the ordering doesn't need to be higher and with other point (in the
code) the operations need to synchronise.
Also increases atomic ordering in `ThreadWaker::wake`
For `ThreadWaker::wake` the `load` is increased from `Relaxed` to `Acquire` to
sync with the `store` in `ThreadWaker::mark_polling`.
=> Document all usages of atomics

src/lib.rs, src/net/tcp/stream.rs
The length was calculated once before the sendfile loop. However in the
loop the start variable was modified, on which the length depends. This
mean more bytes then wanted could be send as the start was updated, but
the length was not.
To fix this simply move the length calculation inside the loop.
=> Fix Future impl for SendFileAll

Cargo.toml, examples/6_process_signals.rs, src/net/tcp/server.rs, src/rt/coordinator.rs, src/rt/local/mod.rs, src/rt/local/scheduler/inactive.rs, src/rt/local/scheduler/mod.rs, src/rt/local/timers.rs, src/rt/shared/mod.rs, src/rt/shared/scheduler/inactive.rs, src/rt/shared/scheduler/mod.rs, src/rt/shared/scheduler/runqueue.rs, src/rt/shared/timers.rs, src/rt/signal.rs, src/rt/worker.rs, src/trace.rs
Adds `rt::Signal::{User1, User2}` to support the `SIGUSR1` and `SIGUSR2` process signals.
Changes the runtime to dump metrics about the runtime when it receives a SIGUSR2 signal. This done using `kill -USR2 $PID`.
The output is ugly and needs improvement, but it's a start.
=> Output runtime metrics on SIGUSR2 process signal

.github/workflows/ci.yml, src/lib.rs, src/rt/coordinator.rs, src/rt/local/mod.rs, src/rt/mod.rs, src/rt/setup.rs
Adds:
* Heph version.
* OS.
* Hostname.
* Architecture.
* Process ID.
* Parent process ID.
* Uptime.
* thread and process CPU usage
Also switches the CI to use stable rustfmt as the nightly version is sometimes not available.
=> Add more runtime metrics

src/rt/local/mod.rs, tests/functional.rs, tests/functional/test.rs
This makes testing functions such as `try_spawn_local`, `try_spawn` and
`spawn_future` a lot more useful.
=> Catch panics in running spawn actors and Futures

Cargo.toml, src/rt/coordinator.rs
Add a host or machine id to the coordinator metrics.
On Linux this uses the `/etc/hostid` file, which is a systemd specific
file. More documentation at
https://www.freedesktop.org/software/systemd/man/machine-id.html.
For FreeBSD we use `/etc/machine-id`, which isn't actually documented
anywhere, but has an open issue to do so:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255293.
On macOS we can use the `gethostuuid(2)` system call.
=> Add host id to Coordinator metrics

http/src/header.rs, http/tests/functional/client.rs, http/tests/functional/header.rs, http/tests/functional/server.rs
First renames `Headers::get_value` to `get_bytes` to free up the name. Next it adds back `Headers::get_value`, but this version returns a parsed header value, using the `FromHeaderValue` trait.
=> Change Headers::get_value

src/rt/process/future.rs, src/supervisor.rs, tests/util/mod.rs
Most futures are properly named, so we can use the same logic as we do
for ActorProcess.
=> Implement Process::name for FutureProcess

http/src/head/mod.rs, http/tests/functional/head.rs
Convenience method to get the header from the request or response.
=> Add {RequestHead, ResponseHead}::header

http/Cargo.toml, http/src/lib.rs, http/src/server.rs
Avoids us having to zero the empty headers array.
Closed #497.
=> Use httparse::Request::parse_with_uninit_headers

http/src/body.rs
Has a couple of FIXMEs and needs tests.
Updates #494.
=> Add initial implementation of ChunkedBody

http/examples/route.rs, http/src/server.rs
Convenience method to respond with a complete Response. This method is
not a performant as respond, which should still be seen as the default,
as it takes ownership of the headers (which can allocate) even though it
doesn't need to.
=> Add server::Connection::respond_with

http/src/head/header.rs, http/src/lib.rs, http/src/str.rs, http/tests/functional/header.rs
This commit introduces a new type called Str which is a combination of
String and str in the same type.
The HeaderName type uses it to reduce its size from 32 to 16 bytes.
=> Reduce the size of HeaderName

Makefile, src/actor_ref/mod.rs
commit c085bbcba275c54f3dd1cccf1b706023203b6b8a
Author: Thomas de Zeeuw <thomasdezeeuw@gmail.com>
Date:   Fri Jan 21 18:56:25 2022 +0100
Reduce the allocations joining a mapped ActorRef
Similar to what we did for sending we simply check if the other side is
disconnected before making an allocation for the future.
commit 85296239a17fdd905b06b3bf6dc95fc6b72abeea
Author: Thomas de Zeeuw <thomasdezeeuw@gmail.com>
Date:   Fri Jan 21 18:42:03 2022 +0100
Reduce the allocations sending with a mapped ActorRef
Before creating a Future attempt to send the message, if this succeeds
or fails unrecoverably (disconnected), we don't have to make the
allocation and can return a result directly.
Updates #338.
=> Reduce allocations mapped actor ref sending and joining

Makefile, src/rt/local/mod.rs, src/rt/mod.rs, src/rt/process/actor.rs, src/rt/process/future.rs, src/rt/process/mod.rs, src/rt/shared/mod.rs, src/rt/shared/scheduler/inactive.rs, src/supervisor.rs, tests/functional/runtime.rs
commit 1e3484ee48571b53efb31f3f52e9d2d90f7ffd83
Author: Thomas de Zeeuw <thomasdezeeuw@gmail.com>
Date:   Sun Feb 13 15:16:57 2022 +0100
Catch panics in spawned Futures
commit 7a19f06d09a0f112a8b1e50151aec09eef6fa9ba
Author: Thomas de Zeeuw <thomasdezeeuw@gmail.com>
Date:   Sun Feb 13 15:39:30 2022 +0100
Don't run a restarted actor
Instead mark it as ready to run.
This prevents a loop in which the actor always returns an error, but is
also always restart (which is a bad supervisor implementation, but
still). This change prevents starvation of the other processes.
commit 97a808b21806df52c4547de485dcbb0a019acba6
Author: Thomas de Zeeuw <thomasdezeeuw@gmail.com>
Date:   Sun Feb 13 15:49:01 2022 +0100
Refactor ActorProcess logic
Moving most of it out of the Process::run implementation into …
=> Catch unwind

Cargo.toml, Makefile, remote/src/net_relay/mod.rs, remote/src/net_relay/routers.rs, rust-toolchain.toml, src/actor/mod.rs, src/bytes.rs, src/lib.rs, src/net/tcp/listener.rs, src/rt/local/scheduler/mod.rs, src/rt/setup.rs, src/rt/shared/scheduler/mod.rs, src/rt/sync_worker.rs, src/spawn/options.rs, src/test.rs, src/timer.rs, src/trace.rs, src/util.rs, tests/examples.rs, tests/functional.rs, tests/functional/runtime.rs, tests/util/mod.rs, tools/src/bin/convert_trace.rs
commit 01cfdd40c48ea13401a180c5e08ea4c43081aadb
Author: Thomas de Zeeuw <thomasdezeeuw@gmail.com>
Date:   Fri Feb 25 10:31:40 2022 +0100
Disable Heph-http crate in Cargo workspace
It's stuck on an older version of rustc for now.
commit 21ec141cd81272e6257d1a434e06f831eba6da54
Author: Thomas de Zeeuw <thomasdezeeuw@gmail.com>
Date:   Fri Feb 25 10:31:10 2022 +0100
Replace std::stream::Stream with AsyncIterator
It's been renamed and moved.
commit 9cbbcd00e59abe0dfbe0bdc66eea77b85cf1d4d9
Author: Thomas de Zeeuw <thomasdezeeuw@gmail.com>
Date:   Fri Feb 25 10:37:34 2022 +0100
Add required Self lifetime
Wasn't required in previous rustc versions.
commit 9f3add7182f12d8051c18bba36f8dfae8631e7d6
Author: Thomas de Zeeuw <thomasdezeeuw@gmail.com>
Date:   Fri Feb 25 10:37:59 2022 +0100
Remove …
=> Rustc update

.github/install.bash, Cargo.toml, Makefile, http/Cargo.toml, remote/Cargo.toml, remote/src/net_relay/mod.rs, src/actor/context.rs, src/actor/future.rs, src/actor/mod.rs, src/lib.rs, src/net/tcp/stream.rs, src/pipe.rs, src/rt/local/timers.rs, src/rt/worker.rs, src/supervisor.rs, src/test.rs, tests/examples.rs, tests/functional.rs, tests/functional/pipe.rs, tests/message_loss.rs, tests/regression.rs
This allows the actor, actor_ref and supervisor module to be used independent of the runtime. This allows, e.g., combining Heph with Tokio.
=> Add runtime feature

rt/src/access.rs, rt/src/lib.rs
This means we'll have less types in the root of the heph-rt crate.
=> Make access module public

rt/src/lib.rs, rt/src/net/mod.rs, rt/src/net/tcp/listener.rs, rt/src/net/tcp/stream.rs, rt/src/net/udp.rs, rt/src/pipe.rs, rt/src/systemd.rs, rt/src/timer.rs, rt/tests/functional/pipe.rs, rt/tests/functional/tcp/listener.rs, rt/tests/functional/tcp/stream.rs, rt/tests/functional/timer.rs, rt/tests/functional/udp.rs, src/actor/mod.rs, src/actor/sync.rs
Currently lives at the root, might need to find a better place for it
later.
Closes #548.
=> Move actor::Bound trait to heph-rt crate

rt/Cargo.toml, rt/src/io/mod.rs
Fixes the leaking of a10::SubmissionQueue. Also avoids the use of some unsafe.
=> Use a10::io::Std{io,out,err}

rt/src/channel.rs
Since it's now backed by crossbeam's channel any way.
We can't replace the local waker's channel as the channel in std lib doesn't provide an is_empty method on the receiver, which is required to determine the timeout when polling for OS events.
=> Replace crossbeam_channel with the channel in std lib

examples/3_sync_actor.rs, examples/4_restart_supervisor.rs, rt/examples/4_sync_actor.rs, rt/examples/6_process_signals.rs, rt/examples/7_restart_supervisor.rs, rt/examples/8_tracing.rs, rt/src/access.rs, rt/src/lib.rs, rt/src/spawn/mod.rs, rt/src/spawn/options.rs, rt/src/sync_worker.rs, rt/src/test.rs, rt/src/trace.rs, rt/tests/functional/runtime.rs, rt/tests/functional/sync_actor.rs, rt/tests/process_signals.rs, rt/tests/regression/issue_294.rs, rt/tests/regression/issue_323.rs, src/actor/mod.rs, src/actor_ref/rpc.rs, src/lib.rs, src/supervisor.rs, src/sync.rs, src/test.rs, tests/functional/sync_actor.rs
Create a new `heph::sync` module, which contains all the types related to sync actors, such as `SyncActor` and `SyncContext`. Within that module I've added `SyncActorRunner` (previously called `SyncWorker` and private) and `SyncActorRunnerBuilder` (yes, it's too long), which can be use to run synchronous actors, catching errors, etc.
This also adds panic handling within the `SyncActorRunner`, which required the `SyncSupervisor::decide_on_panic` method. Which is similar to `Supervisor::decide_on_panic` for async actors.
Finally I've added `SyncActor::name` to determine the name of the sync actor. With `ActorFn` this actually produces are reasonable result, with `sync_actor as fn(..) -> _` not so much.
Closes #572
Closes #576
=> Rework synchronous actors in heph

rt/src/lib.rs, rt/src/process/mod.rs, rt/src/scheduler/shared/tests.rs, rt/src/scheduler/tests.rs, rt/src/shared/mod.rs, rt/src/spawn/options.rs, src/actor/mod.rs, src/actor/tests.rs, src/future.rs, src/lib.rs, src/quick_start.rs, src/sync.rs
TODO:
* In the heph crate, see `spawn_sync_actor`
* In heph-rt, see `rt::sync_worker::start`.
Closes #513
=> Add option to change actor's inbox size

examples/3_sync_actor.rs, examples/4_restart_supervisor.rs, rt/examples/4_sync_actor.rs, rt/examples/6_process_signals.rs, rt/examples/7_restart_supervisor.rs, rt/examples/8_tracing.rs, rt/src/access.rs, rt/src/lib.rs, rt/src/trace.rs, rt/tests/functional/runtime.rs, rt/tests/functional/sync_actor.rs, rt/tests/process_signals.rs, rt/tests/regression/issue_294.rs, rt/tests/regression/issue_323.rs, src/actor/mod.rs, src/actor_ref/rpc.rs, src/sync.rs, tests/functional/sync_actor.rs
Similar to actor::Context.
Closes #591
=> Rename SyncContext to sync::Context

.github/workflows/ci.yml, .github/workflows/heph.yml, .github/workflows/http.yml, .github/workflows/inbox.yml, .github/workflows/remote.yml, .github/workflows/rt.yml, .github/workflows/test/action.yml, .github/workflows/test_sanitizer/action.yml, Makefile.include, rt/Cargo.toml, rt/src/channel.rs
=> Split up CI

.github/workflows/inbox.yml, .github/workflows/test/action.yml, .github/workflows/test_miri/action.yml, .github/workflows/test_sanitizer/action.yml, Makefile.include
=> Enable CI for Heph-inbox

rt/src/fs/watch.rs
Even if the user didn't retrieve them.
This is mainly important for IN_IGNORED events which makes us deleted paths that are no longer watched.
=> Process all watch events

rt/src/fs/mod.rs, rt/src/net/tcp/listener.rs, rt/src/net/tcp/stream.rs, rt/src/net/udp.rs, rt/src/net/uds/datagram.rs, rt/src/net/uds/listener.rs, rt/src/net/uds/stream.rs, rt/tests/functional/fs.rs, rt/tests/functional/tcp/listener.rs, rt/tests/functional/tcp/stream.rs, rt/tests/functional/udp.rs, rt/tests/functional/uds/datagram.rs, rt/tests/functional/uds/listener.rs, rt/tests/functional/uds/stream.rs
This implements a `from_std` method for various types that can be created based on a similar type found in the standard library.
=> Implement from_std for various types

rt/src/access.rs, rt/src/lib.rs, rt/tests/functional.rs, rt/tests/functional/access.rs
This allows the creation of ThreadLocal and ThreadSafe from the Runtime and RuntimeRef types.
This is required for manual creation of actors using ActorFutureBuilder type and customer runtime.
=> Implement From<Runtime(Ref)> for Thread{Local,Safe}

inbox/src/lib.rs, remote/src/net_relay/routers.rs, rt/src/coordinator.rs, rt/src/local/mod.rs, rt/tests/functional/actor_group.rs, src/actor_ref/mod.rs, tests/functional.rs, tests/functional/actor_group.rs
See individual commits.
Closes #567
Closes #565
=> Expand ActorGroup API 

inbox/src/lib.rs, inbox/src/tests.rs, inbox/src/waker.rs, inbox/tests/util/mod.rs, rt/src/scheduler/inactive.rs, rt/src/scheduler/shared/inactive.rs, rt/src/test.rs, rt/src/timers/tests.rs, rt/src/wakers/shared.rs, rt/tests/functional/runtime.rs, rt/tests/process_signals.rs, src/actor/tests.rs, src/test.rs
This replaces all SeqCst atomic operations with Release, Acquire or AcqRel.
Also see https://github.com/rust-lang/rust/pull/122729.
=> Relax SeqCst atomic ordering

src/lib.rs, src/supervisor.rs
This ensures that the actor is also restarted in case of a panic and
that the panic is properly logged.
=> Implement decide_on_panic for restart_supervisor!

Makefile, Makefile.include
Create a test coverage report in HTML.
=> Add coverage and coverage_all targets
