- src/actor_ref/mod.rs
- tests/functional/actor_ref.rs
> Add ActorRef::is_connected

- tests/functional.rs
- tests/functional/tcp/stream.rs
- tests/util/mod.rs
> Make tcp::stream::try_recv less flaky

- src/rt/channel.rs
- src/rt/waker.rs
- src/test.rs
- src/timer.rs
- tests/functional/actor_ref.rs
- tests/functional/tcp/stream.rs
- tests/message_loss.rs
> Add some more tests

- src/net/tcp/stream.rs
- tests/functional/tcp/stream.rs
macOS sometimes returns EINVAL when the socket is not yet connected when
calling getpeername in the Connect Future. Since we're ensure that the
arguments passed to getpeername are valid it's safe to ignore this error
and threat as socket is not (yet) connected.
Also deflakes the connect_connection_refused test.
> Ignore EINVAL in TcpStream::connect

- src/actor_ref/mod.rs
This reduces the allocation from 112 bytes to 80 bytes.
Updates #338.
> Introduce MappedSendValue struct

- src/rt/process/mod.rs
Clippy was complaining about it.
> Replace Into<Token> for Process with From<ProcessId> for Token

- src/actor/context.rs
- src/net/tcp/server.rs
- src/net/tcp/stream.rs
- src/rt/access.rs
- src/rt/mod.rs
- src/rt/worker.rs
- src/test.rs
> Support setting CPU affinity

- examples/8_tracing.rs
- examples/README.md
- src/actor/mod.rs
- src/actor/sync.rs
- src/actor/tests.rs
- src/rt/mod.rs
- src/rt/sync_worker.rs
- src/rt/trace.rs
- src/test.rs
> Add SyncContext::{start,finish}_trace 

- src/test.rs
Initialises a thread-safe actor.
> Add test::init_actor

- src/actor/context.rs
- src/actor/messages.rs
- src/actor/mod.rs
- src/actor/sync.rs
- src/actor_ref/mod.rs
- src/actor_ref/rpc.rs
- src/lib.rs
- src/net/mod.rs
- src/net/tcp/listener.rs
- src/net/tcp/server.rs
- src/net/tcp/stream.rs
- src/net/udp.rs
- src/rt/error.rs
- src/rt/mod.rs
- src/rt/setup.rs
- src/rt/shared/mod.rs
- src/rt/worker.rs
- src/supervisor.rs
- src/test.rs
- src/timer.rs
- src/trace.rs
Did a complete review of the public API documentation. This commit
touches basically all of it.
> Various doc improvement

- Cargo.toml
- src/actor_ref/mod.rs
- tests/functional/actor_group.rs
- tests/functional/actor_ref.rs
Closes #265.
Closes #358.
Closes #359.
> Expand ActorGroup API

- Makefile
- src/actor/mod.rs
- src/actor/tests.rs
- src/rt/timers.rs
- tests/functional/timer.rs
Contains the following commits:
* Add RUN variable to Make dev
* Support generic parameters in actor::name
* Remove value from test Pending
* Remove unwrap from rt::Timers::remove_deadline
> Small pieces of work

- examples/4_sync_actor.rs
- examples/6_process_signals.rs
- examples/7_restart_supervisor.rs
- examples/8_tracing.rs
- src/actor/mod.rs
- src/actor/sync.rs
- src/actor_ref/rpc.rs
- src/rt/mod.rs
- src/rt/options.rs
- src/rt/signal.rs
- src/rt/sync_worker.rs
- src/supervisor.rs
- src/test.rs
- src/trace.rs
- tests/functional/runtime.rs
- tests/functional/sync_actor.rs
- tests/regression/issue_294.rs
- tests/regression/issue_323.rs
Removes the stuttering, e.g. sync sync actor.
Closes #389.
> Move SyncActor and SyncContext into actor module

- src/lib.rs
- src/rt/mod.rs
- src/rt/setup.rs
See issue #388 for rationale.
Updates #388.
> Move Runtime usage documentation to rt module

- README.md
- src/actor_ref/mod.rs
- src/lib.rs
- src/quick_start.rs
> Add Quick Start guide

- Makefile
Although currently Heph isn't in a workspace I often copy this code to
projects that do work with workspaces. So, I want a single version that
works everywhere.
> Support Make coverage in workspaces

- tests/functional/bytes.rs
- tests/functional/sync_actor.rs
- tests/functional/tcp/stream.rs
- tests/functional/udp.rs
> Add additional tests

- src/net/mod.rs
- src/net/tcp/stream.rs
> Add more documentation to net module

- src/rt/shared/scheduler/inactive.rs
- src/rt/shared/scheduler/mod.rs
The implementation still uses a Hash Array Mapped Trie (HAMT), but now
uses atomic pointers.
Updates #406.
> Remove lock from Inactive tree in shared scheduler

- src/actor_ref/mod.rs
- src/actor_ref/rpc.rs
- src/rt/local/mod.rs
- tests/functional/actor_ref.rs
> Small improvements

- tests/examples.rs
This first reads the greeting messages to ensure the runtime had time to start up before sending the process signal.
Updates #374
> Deflake test_6_process_signals

- tests/examples.rs
> Deflake test example 2 my ip

- tests/functional/tcp/stream.rs
On FreeBSD the initial call to TcpStream::connect in some cases already
return a connection refused error, which is an acceptable outcome.
> Deflake connect_connection_refused test

- src/rt/shared/scheduler/inactive.rs
The ThreadSanitizer complained about there being a possible data race
when using `Relaxed` ordering. Although I'm not 100% convinced this is
required, better safe than sorry.
> Increase strength of load operations in shared::Inactive tree

- src/rt/local/scheduler/inactive.rs
Now it uses the same function as that in the shared Inactive tree.
Removes the loop and replaces it with a single trailing_zeros function
(and instruction).
> Refactor diff_branch_depth in local Inactive tree

- http/src/client.rs
- http/src/server.rs
- src/actor/mod.rs
- src/test.rs
Simple supervisor that panics on each error.
> Add test::PanicSupervisor

- .cirrus.yml
- Cargo.toml
- src/test.rs
Depends https://github.com/Thomasdezeeuw/inbox/pull/26.
Fixes #456
> Update Heph-inbox to v0.2.0

- src/actor_ref/mod.rs
- tests/functional/actor_ref.rs
Returns a `Future` that waits until the actor finishes running. Acts
similar to a `JoinHandle` of a thread.
> Add ActorRef::join

- Cargo.toml
- src/test.rs
- tests/functional/actor_ref.rs
- tests/functional/tcp/listener.rs
- tests/functional/tcp/server.rs
- tests/functional/tcp/stream.rs
- tests/functional/udp.rs
- tests/util/mod.rs
Instead use the test spawn functions.
> Remove loop polling from tests

- src/actor_ref/mod.rs
- src/test.rs
- tests/functional/actor_group.rs
- tests/functional/test.rs
Blocked on https://github.com/Thomasdezeeuw/heph/pull/471 for the update of Heph-inbox.
> Add ActorGroup::join_all

- http/examples/my_ip.rs
- http/src/head/header.rs
- http/src/lib.rs
- http/src/server.rs
- http/tests/functional/head.rs
- http/tests/functional/header.rs
- http/tests/functional/server.rs
> Expand HTTP Headers API

- http/src/body.rs
- http/src/head/method.rs
- http/src/head/mod.rs
- http/src/head/status_code.rs
- http/src/request.rs
- http/src/response.rs
- http/tests/functional.rs
- http/tests/functional/body.rs
- http/tests/functional/head.rs
- http/tests/functional/message.rs
- http/tests/functional/method.rs
- http/tests/functional/status_code.rs
Some more convenience methods.
Includes #487 (with tests).
> Expand HTTP API

- http/examples/route.rs
- http/src/lib.rs
- http/src/response.rs
- http/src/route.rs
- http/src/server.rs
- http/tests/functional.rs
- http/tests/functional/route.rs
Macro to do simple routing of a request to the correct.
> Add route! macro

- examples/redis.rs
Very basic Redis server clone.
> Add Redis example

- src/actor_ref/mod.rs
- tests/functional/actor_ref.rs
Both methods allow for a mapping function to be used to map the message
type from one to the next.
> Add ActorRef::{map_fn, try_map_fn}

- Cargo.toml
- remote/Cargo.toml
- remote/Makefile
- remote/src/lib.rs
- remote/src/net_relay/mod.rs
- remote/src/net_relay/routers.rs
- remote/src/net_relay/tcp.rs
- remote/src/net_relay/udp.rs
- remote/src/net_relay/uuid.rs
- rust-toolchain.toml
- src/actor_ref/mod.rs
Updates #474
Updates #473
Updates #188
Closes #214
> Add beginning of Heph-remote crate

- src/supervisor.rs
A simple supervisor that logs the error and stops the actor.
> Add StopSupervisor

- LICENSE
- Makefile
- examples/9_systemd.rs
- examples/README.md
- src/lib.rs
- src/rt/coordinator.rs
- src/systemd.rs
It provides utilities to support systemd (https://systemd.io).
> Systemd support

- README.md
Feel free to take or leave any of these suggestions, @Thomasdezeeuw.
You can apply piecemeal at your own discretion.
> doc: Minor improvements to README readability

- README.md
- src/lib.rs
- src/quick_start.rs
> Various documentation improvements

- rt/src/process/mod.rs
- src/future.rs
- src/sync.rs
> Various small improvements

- examples/3_sync_actor.rs
- rt/examples/4_sync_actor.rs
- rt/examples/8_tracing.rs
- rt/src/lib.rs
- rt/src/spawn/options.rs
- rt/src/sync_worker.rs
- src/lib.rs
- src/sync.rs
> Replace SyncWorker with SyncActorRunner in heph-rt

- src/actor/mod.rs
- src/sync.rs
No longer used by heph-rt.
Updates #549
> Remove some unstable public API

- remote/src/net_relay/uuid.rs
- rt/src/test.rs
- src/future.rs
- src/lib.rs
- src/sync.rs
And replace it with safer alternatives.
> Remove as in places

- rt/tests/process_signals.rs
By adding a never ending process, i.e. one that always returns Poll::Pending, we ensure that the runtime doesn't shutdown due to no processes being ready to run.
> Fix flaky no_signal_handlers test

- rt/src/signal.rs
This is pretty much all of them at the moment, that can be caught at
least.
> Add 20 more Signals

- rt/src/access.rs
- rt/tests/functional/timer.rs
> Implement Access for &mut T

- rt/tests/functional/actor_ref.rs
- src/actor_ref/rpc.rs
Failable version of RpcMessage::handle.
> Add RpcMessage::try_handle

- rt/src/fs/mod.rs
- rt/src/fs/watch.rs
- rt/src/net/tcp/listener.rs
- rt/src/net/tcp/stream.rs
- rt/src/net/udp.rs
- rt/src/net/uds/datagram.rs
- rt/src/net/uds/listener.rs
- rt/src/net/uds/stream.rs
- rt/src/pipe.rs
> Implement AsFd for all fd types

- rt/Cargo.toml
- rt/src/fs/mod.rs
- rt/src/net/tcp/listener.rs
- rt/src/net/tcp/stream.rs
- rt/src/net/udp.rs
- rt/src/net/uds/datagram.rs
- rt/src/net/uds/listener.rs
- rt/src/net/uds/stream.rs
- rt/src/pipe.rs
> Implement try_clone for fd types

- Cargo.toml
- http/Cargo.toml
- rt/Cargo.toml
- rt/examples/2_my_ip.rs
- rt/examples/redis.rs
- rt/src/coordinator.rs
- rt/src/lib.rs
- rt/src/local/mod.rs
- rt/src/net/tcp/server.rs
- rt/src/process/mod.rs
- rt/src/setup.rs
- rt/src/shared/mod.rs
- rt/src/systemd.rs
- rt/src/worker.rs
Requires updating to log v0.4.21 and std-logger v0.5.3.
> Update to log's stable KV feature

- http/tests/functional/route.rs
- http/tests/functional/transform.rs
- rt/src/pipe.rs
- rt/src/test.rs
- rt/tests/functional/fs.rs
- rt/tests/functional/fs_watch.rs
- rt/tests/functional/tcp/listener.rs
- rt/tests/functional/tcp/stream.rs
- rt/tests/functional/test.rs
- rt/tests/functional/timer.rs
- rt/tests/functional/udp.rs
- rt/tests/functional/uds/datagram.rs
- rt/tests/functional/uds/listener.rs
- rt/tests/functional/uds/stream.rs
Makes it a lot easier to use in testing.
> Continue unwinding in test::block_on_* functions

- rt/Cargo.toml
- rt/src/coordinator.rs
- rt/src/io/buf.rs
- rt/src/io/buf_pool.rs
- rt/src/io/mod.rs
- rt/src/setup.rs
- rt/src/shared/mod.rs
- rt/src/worker.rs
- rt/tests/functional/fs.rs
- rt/tests/functional/io.rs
- src/actor_ref/mod.rs
Specialised read buffer pool that wraps around a10's ReadBufPool, which wraps around io_uring read buffer pool.
> Add ReadBufPool

- rt/src/fs/watch.rs
- rt/src/shared/mod.rs
- rt/src/test.rs
- rt/src/wakers/tests.rs
> Various improvement to the test module of heph_rt

- Cargo.toml
- src/supervisor.rs
- tests/message_loss.rs
Cleaning up my local branches.
> Small cleanups

- src/lib.rs
> Remove unused impl_trait_in_assoc_type feature

- .github/workflows/ci.yml
- .github/workflows/heph.yml
- .github/workflows/http.yml
- .github/workflows/inbox.yml
- .github/workflows/remote.yml
- .github/workflows/rt.yml
- Makefile.include
> Use Ubuntu 24.04 for CI
